version: '2'
services:
  db:
    image: postgres:9.6
  api:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    command: sh -c 'rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0'
    depends_on:
      - db
    volumes:
      - .:/usr/local/src
